name: vc_playground
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - jupyterlab
  - requests
  - scipy
  - seaborn
  - pip:
      - -r requirements.txt